include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    missing_required_param: error
    missing_return: error
    dead_code: warning
  exclude:
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.env.dart"

linter:
  rules:
    # Style
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    annotate_overrides: true
    avoid_dynamic_calls: true
    avoid_empty_else: true
    avoid_print: true
    avoid_redundant_argument_values: true
    avoid_relative_lib_imports: true
    avoid_returning_null_for_future: true
    avoid_shadowing_type_parameters: true
    avoid_types_as_parameter_names: true
    avoid_unnecessary_containers: true
    avoid_void_async: true
    cancel_subscriptions: true
    close_sinks: true
    directives_ordering: true
    exhaustive_cases: true
    flutter_style_todos: true
    no_duplicate_case_values: true
    no_logic_in_create_state: true
    prefer_const_constructors: true
    prefer_const_constructors_in_immutables: true
    prefer_const_declarations: true
    prefer_const_literals_to_create_immutables: true
    prefer_final_fields: true
    prefer_final_locals: true
    prefer_if_null_operators: true
    prefer_single_quotes: true
    prefer_spread_collections: true
    sized_box_for_whitespace: true
    sort_child_properties_last: true
    unnecessary_const: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_nullable_for_final_variable_declarations: true
    unnecessary_string_escapes: true
    unnecessary_string_interpolations: true
    use_full_hex_values_for_flutter_colors: true
    use_key_in_widget_constructors: true
