name: sport_connect
description: SportConnect — plataforma mobile de comunidade esportiva
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # State management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Navigation
  go_router: ^13.2.0

  # HTTP
  dio: ^5.4.3
  pretty_dio_logger: ^1.3.1

  # Local storage
  hive_flutter: ^1.1.0

  # Secure storage
  flutter_secure_storage: ^9.0.0

  # Code generation — models
  freezed_annotation: ^2.4.1
  json_annotation: ^4.9.0

  # Environment variables
  envied: ^0.5.4

  # UI
  flutter_svg: ^2.0.10+1
  cached_network_image: ^3.3.1

  # i18n
  intl: ^0.20.2

  # Auth social
  google_sign_in: ^6.2.1
  sign_in_with_apple: ^6.1.1

  # Maps — Mapbox Maps SDK (vector tiles, cache automático, 50k map loads/mês grátis)
  mapbox_maps_flutter: ^2.3.0

  # Location
  geolocator: ^11.0.0

  # Charts
  fl_chart: ^0.67.0

  # Firebase
  firebase_core: ^2.30.1
  firebase_auth: ^4.19.6
  cloud_firestore: ^4.17.5
  firebase_messaging: ^14.9.1

  # Animations
  confetti: ^0.7.0

  # Media
  image_picker: ^1.1.2

  # QR Code
  qr_flutter: ^4.1.0

  # Utils
  timeago: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  freezed: ^2.5.2
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0
  envied_generator: ^0.5.4
  golden_toolkit: ^0.15.0
  mocktail: ^1.0.4

flutter:
  uses-material-design: true
  generate: true
  # fonts: descomentado quando baixar os arquivos .ttf da Inter
  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
